# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import location_server_pb2 as protos_dot_location__server__pb2


class location_serverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.read = channel.unary_unary(
                '/locationserver.location_server/read',
                request_serializer=protos_dot_location__server__pb2.read_request.SerializeToString,
                response_deserializer=protos_dot_location__server__pb2.read_response.FromString,
                )
        self.write = channel.unary_unary(
                '/locationserver.location_server/write',
                request_serializer=protos_dot_location__server__pb2.write_request.SerializeToString,
                response_deserializer=protos_dot_location__server__pb2.write_response.FromString,
                )
        self.update = channel.unary_unary(
                '/locationserver.location_server/update',
                request_serializer=protos_dot_location__server__pb2.write_request.SerializeToString,
                response_deserializer=protos_dot_location__server__pb2.write_response.FromString,
                )


class location_serverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_location_serverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'read': grpc.unary_unary_rpc_method_handler(
                    servicer.read,
                    request_deserializer=protos_dot_location__server__pb2.read_request.FromString,
                    response_serializer=protos_dot_location__server__pb2.read_response.SerializeToString,
            ),
            'write': grpc.unary_unary_rpc_method_handler(
                    servicer.write,
                    request_deserializer=protos_dot_location__server__pb2.write_request.FromString,
                    response_serializer=protos_dot_location__server__pb2.write_response.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=protos_dot_location__server__pb2.write_request.FromString,
                    response_serializer=protos_dot_location__server__pb2.write_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'locationserver.location_server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class location_server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/locationserver.location_server/read',
            protos_dot_location__server__pb2.read_request.SerializeToString,
            protos_dot_location__server__pb2.read_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/locationserver.location_server/write',
            protos_dot_location__server__pb2.write_request.SerializeToString,
            protos_dot_location__server__pb2.write_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/locationserver.location_server/update',
            protos_dot_location__server__pb2.write_request.SerializeToString,
            protos_dot_location__server__pb2.write_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
